language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
  - osx

before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then
    sudo apt-get update -qq;
    sudo apt-get install -y libglew-dev libglfw3-dev libglfw3 libglm-dev;
  fis
- if [ $TRAVIS_OS_NAME = osx ]; then
    brew update;
    brew install glew glfw glm;
  fi

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j4